### ISSUE TITLE
Error in gpsFISH_optimize on tutorial data

### ISSUE THREAD

**Issue by pakiessling** [kharchenkolab/gpsFISH#15]
Hi I receive multiple errors while following the tutorial.

```
unused argument full_count_table

argument "cell_list" is missing
```

Has the function changed?

**Comment by YidaZhang0628** [comment]
Based on this error message, it seems that you installed the development version of gpsFISH but followed the tutorial of the main version. The function `gpsFISH_optimize` is slightly different between the two versions. You can either follow this [tutorial](https://github.com/kharchenkolab/gpsFISH/blob/devel/doc/gene_panel_selection.md) for the development version or re-install the main version of gpsFISH using the command below:
`install.packages('devtools')`
`devtools::install_github("kharchenkolab/gpsFISH")`
