### ISSUE TITLE
y variable has to contain at least one observation per class for estimation process

### ISSUE THREAD

**Issue by pakiessling** [kharchenkolab/gpsFISH#17]
Hi @YidaZhang0628 ,

thanks to all of your help I now have gpsFISH running quite nicely.

For the evaluation of a panel I tried to increase the number of cross-validations from 5 to 10.
I then received the error: `y variable has to contain at least one observation per class for estimation process`

Thanks!

**Comment by YidaZhang0628** [comment]
It is good to know that you can run gpsFISH on your dataset. For your question, what is the command you used and the size (number of cells) of your smallest cell type after subsampling?

**Comment by pakiessling** [comment]
This is the command:
```
result <- fitness(string=index_list,
        full_count_table=as.data.frame(t(sc_count)),
        cell_cluster_conversion=sc_cluster
        ,nCV=10
        , rate=0.15,
        cluster_size_min=50,
        relative_prop=relative_prop,
        two_step_sampling_type=two_step_sampling_type)
```
I am unsure how to retrieve the number of cells after `fitness()` subsamples.
The smallest number before subsampling is 718 , so if cluster_size_min=50 works it should be 50

**Comment by pakiessling** [comment]
I just noticed that `fitness()` wants genes as columns, exactly the other way around than `gpsFISH_optimize()`, my mistake.

I will repeat again

**Comment by YidaZhang0628** [comment]
Thank you for pointing this out. You are right that the documentation on full_count_table is wrong. You should have cells as rows and genes as columns. I have updated it. Sorry for the confusion.

**Comment by pakiessling** [comment]
@YidaZhang0628  No problem, any idea about the y variable thing? Can I make gpsfish print what it is doing with the subsampling somehow?

**Comment by YidaZhang0628** [comment]
If you increase `rate` and `cluster_size_min`, is the error still there? Regarding the subsampling part, it is simply the original cell type size times the rate and adjusted by the lower and upper bound. In your case, the lower bound is 718*0.15 which is about 108 cells. This should be enough for 10 cross-validations. If increasing `rate` and `cluster_size_min` doesn't solve the problem, can you share the file to reproduce this error? I can take a look.

**Comment by pakiessling** [comment]
@YidaZhang0628 even after doubling the subsample - same error :(

Here is the code im running: https://github.com/pakiessling/misc/blob/main/gpsfish.R
Here is the dataset (600 MB) https://rwth-aachen.sciebo.de/s/wpNMOYlxOqXiKtH

**Comment by YidaZhang0628** [comment]
I took a look at the code and found that this is caused by a mismatch between cross-validation names when there are 10 or more cross-validations. I have fixed this issue. If you re-install the main version, you will be able to run your code without a problem.

**Comment by pakiessling** [comment]
Perfect. Thank you!
