### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by simomounir** [kharchenkolab/gpsFISH#19]
Hi all,

I wanted to run the package and try it but unfortunately I ran into am installation bug. Something around these lines:

\processx.dll: Permission denied
3: In i.p(...) : installation of package ‘rstan’ had non-zero exit status
4: In i.p(...) : installation of package ‘ranger’ had non-zero exit status
5: In i.p(...) : installation of package ‘....../gpsFISH_0.1.0.tar.gz’ had non-zero exit status

Any sol;ution? Anyone who ran into the same issue and solved it?

Thanks in advance for looking into this:

More details:

platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          1.2                         
year           2021                        
month          11                          
day            01                          
svn rev        81115                       
language       R                           
version.string R version 4.1.2 (2021-11-01)
nickname       Bird Hippie

**Comment by YidaZhang0628** [comment]
Based on the information, it seems that the installation failed because there are problems when installing `rstan` and `ranger`. Can you try to install these two packages separately and then install gpsFISH?

**Comment by simomounir** [comment]
I tried installing the packages separately, and yet not success. Tried to install without compiling and it seems to work for now.
